CC = i686-w64-mingw32-gcc
TARGET = 3doh.exe
CFLAGS = -march=pentium -Os -flto -fdata-sections -ffunction-sections -D_WIN32 -DSCALING
CFLAGS += -Isrc -Isrc/freedo
LDFLAGS= -static -lmingw32 -lSDLmain -lSDL -ldxguid -mwindows -lwinmm -lm -s -Wl,-O1,--sort-common,--as-needed,--gc-sections -no-pie -flto -s

OBJS = \
	src/freedo/arm.o \
	src/freedo/DiagPort.o\
	src/freedo/quarz.o\
	src/freedo/Clio.o \
	src/freedo/frame.o \
	src/freedo/Madam.o \
	src/freedo/vdlp.o \
	src/freedo/_3do_sys.o \
	src/freedo/bitop.o \
	src/freedo/DSP.o \
	src/freedo/Iso.o \
	src/freedo/SPORT.o \
	src/freedo/XBUS.o \
	src/freedo/freedo_fixedpoint_math.o \
	src/video.o \
	src/sound.o \
	src/cdrom.o \
	src/timer.o \
	src/input.o \
	src/config.o \
	src/cuefile.o \
	src/font/font_drawing.o \
	src/main.o

all: $(TARGET)

rm-elf:
	-rm -f $(TARGET) $(OBJS)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -r $(OBJS) $(TARGET)
